name: 🐛 Issue Report
description: Report an issue
title: '[Issue]: '
labels: ['issue', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: A clear and concise description of what the issue is
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
