blank_issues_enabled: false
contact_links:
  - name: 👽 Reddit Community
    url: https://www.reddit.com/r/FightClub5e/
    about: Connect with the wider community on Reddit
  - name: 💬 Discord Community
    url: https://discord.gg/6zvbC6KVHJ
    about: Get real-time help and chat with the community
  - name: 🗣️ GitHub Discussions
    url: https://github.com/vidalvanbergen/FightClub5eXML/discussions
    about: For questions, ideas, and general discussions
  - name: 📖 Documentation
    url: https://github.com/vidalvanbergen/FightClub5eXML#readme
    about: Read the documentation before opening an issue
