name: Compile all collections into compendiums
on:
  push:
    branches: [ master ]
    tags:
      - '*'
    paths:
      - 'Collections/**'
      - 'Sources/**'
  workflow_dispatch:

jobs:
  compile_collections:
    name: Compile collections
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y --no-install-recommends xsltproc

      - name: Compile collections into compendiums
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        run: |
          set -euxo pipefail
          chmod +x build-collections.sh
          ./build-collections.sh

      - name: Upload compiled XML files as artifact
        uses: actions/upload-artifact@v7
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        with: 
          name: compendiums-${{ github.ref_name }}
          path: Compendiums/

      # Create a GitHub release when a tag is pushed
      - name: Create versioned release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: Compendiums/*

      - name: Force update nightly tag
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
        run: |
          git tag -f nightly
          git push origin nightly --force

      # Update the nightly release
      - name: Update nightly release
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly release
          files: Compendiums/*
          prerelease: true
          make_latest: true
